---

- name: install packages
  yum:
    name: haproxy
    state: latest

- name: enable packages
  service:
    name: haproxy
    enabled: yes

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy


