- name: add_host
  hosts: all
  #gather_facts: false
  become: true
  roles:
    - add_host

- name: configuration
  hosts: all:!jumpbox
  gather_facts: false
  become: true
  roles:
    - configuration

- name: deploy haproxy
  hosts: frontends
  gather_facts: false
  become: true
  roles:
    - haproxy

- name: deploy apache
  gather_facts: false
  become: true
  hosts: apps
  roles:
    - tomcat

- name: deploy postgres
  #gather_facts: false
  become: true
  hosts: appdbs
  roles:
    - geerlingguy.postgresql

