#- name: configuration
#  hosts: all
#  gather_facts: false
#  become: true
#  roles:
#    - configuration

- name: deploy haproxy
  hosts: frontends
  gather_facts: false
  become: true
  roles:
    - configuration
    - haproxy

- name: deploy apache
  gather_facts: false
  become: true
  hosts: apps
  roles:
    - configuration
    - tomcat

#- name: deploy postgres
#  #gather_facts: false
#  become: true
#  hosts: appdbs
#  roles:
#    - geerlingguy.postgresql

