- hosts: jumpbox
  gather_facts: false
  roles:
   - create_instance

- name: configuration
  hosts: all
  gather_facts: false
  become: true
  roles:
    - configuration

- name: deploy haproxy
  hosts: frontends
  gather_facts: false
  become: true
  roles:
    - haproxy

- name: deploy apache
  gather_facts: false
  become: true
  hosts: apps
  roles:
    - tomcat

#- name: deploy postgres
#  #gather_facts: false
#  become: true
#  hosts: appdbs
#  roles:
#    - geerlingguy.postgresql

