---
  - name: install tomcat
    package:
      name: tomcat
      state: latest

  - name: enable tomcat at boot
    service:
      name: tomcat
      enabled: yes

  - name: create ansible tomcat directory
    file:
      path: "{{ tomcat_root }}"
      state: directory

  - name: copy static index.html to tomcat webapps/ansible/index.html
    template:
      src: "{{ index_template }}"
      dest: "{{ tomcat_root }}/index.html"
      mode: 0644
    notify: restart tomcat
